### PR TITLE
Pass cloned objects into recursive _.deepExtend() calls

### PR DESCRIPTION
**Pull request by kurtmilam**
Related to Issue #10, as well as to this comment on the [gist](https://gist.github.com/kurtmilam/1868955#comment-1356616).

I was passing `obj[prop]` straight into recursive `_.deepExtend()` calls (for properties that were objects or arrays). This resulted in the unwanted modification of intermediate objects and arrays. Passing in `_.clone(obj[prop])` takes care of the problem.

It seems the erratic behavior was introduced along with the fix for Issue #6.

### CODE REVIEW

**Comment by jtfairbank** [comment]
@kurtmilam Any reason this hasn't been merged in yet?

I'm trying to use deepExtend for multiple child config objects, but since the parent is modified each time I call deepExtend the subsequent children contain properties of the previous children that have been erroneously added to the parent.

**Comment by kurtmilam** [comment]
@jtfairbank: @pygy isn't maintaining this repo any more. The last time I spoke with him, he indicated that he wanted shift control of the project over to me, but I haven't heard anything since. I'll drop him an email and see whether he can find the time to pass it back to me, in which case I'll merge the change immediately.

**Comment by pygy** [comment]
@kurtmilam  Actually, [I was waiting for you to delete your fork so that I can transfer ownership](https://github.com/pygy/underscoreDeepExtend/pull/8#issuecomment-50081445)...

Sorry for not merging this earlier. I've now merged this PR so that you can do it without losing your work (or meddling with git to sync things up properly).

**Comment by jtfairbank** [comment]
Cool y'all, glad this is figured out. :+1:

**Comment by pygy** [comment]
Transfer request sent!

**Comment by kurtmilam** [comment]
Accepted - thanks again for the assistance!

Kurt

**Pull request merged**
